### ISSUE TITLE
Found Bug

### ISSUE THREAD

**Issue by ColeTeff** [khimno/YER-GAY-LVL#1]
It will crash if you're too gay

**Comment by khimno** [comment]
It's a feature

**Comment by ColeTeff** [comment]
ITS NOT FIXED BIG GAY GSDHLSRLGHLRHSB

**Comment by khimno** [comment]
I said it is a feature

**Comment by ElementG9** [comment]
This issue is of top priority and must be solved. I pinned the issue and unlocked the conversation so that we can get this serious issue removed.

**Comment by ElementG9** [comment]
yeah we good
